VAT = 0.2

ORDER_DRAFT = 'DRAFT'
ORDER_PLACED = 'PLACED'
ORDER_CANCELED = 'CANCELED'
ORDER_PAID = 'PAID'

ORDER_STATUS = {
    (ORDER_DRAFT, 'DRAFT'),
    (ORDER_PLACED, 'PLACED'),
    (ORDER_CANCELED, 'CANCELED'),
    (ORDER_PAID, 'PAID')}
